cloudmarket/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import login_views
app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', login_views.CreateUserView.as_view(), name='signup'),
]

cloudmarket/market/urls.py
from django.urls import path
from .views import post_views, comment_views, my_views

# 이미지
# from django.conf.urls.static import static
# from django.conf import settings


app_name = 'market'


urlpatterns = [

    path('', post_views.PostList.as_view(), name='postlist'),
    path('<int:pk>/', post_views.PostDetail.as_view(), name = 'postdetail' ),

    path('post/create/', post_views.PostCreate.as_view(), name = 'postcreate' ),
    path('post/update/<int:pk>/', post_views.PostUpdate.as_view(), name='postupdate'),
    path('post/delete/<int:pk>/', post_views.PostDelete.as_view(), name='postdelete'),

    path('comment/create/<int:pk>/', comment_views.CommentCreate.as_view(), name='commentcreate'),
    path('comment/update/<int:pk>/', comment_views.CommentUpdate.as_view(), name='commentupdate'),
    path('comment/delete/<int:pk>/', comment_views.CommentDelete.as_view(), name='commentdelete'),

    path('postlist/', my_views.MyPostList.as_view(), name='mypostlist'),
    path('commentlist/', my_views.MyCommentList.as_view(), name='mycommentlist'),
]

market/urls.py
from django.urls import path
from .views import post_views

# 이미지
# from django.conf.urls.static import static
# from django.conf import settings

# 네임스페이스 추가 - 박지수
app_name = 'market'


urlpatterns = [
    # post_views.py - 박지수
    path('', post_views.PostList.as_view(), name='postlist'),
    path('create/', post_views.PostCreate.as_view(), name = 'postcreate' ),
    path('<int:pk>/', post_views.PostDetail.as_view(), name = 'postdetail' ),
    path('update/<int:pk>/', post_views.PostUpdate.as_view(), name='postupdate'),
    path('delete/<int:pk>/', post_views.PostDelete.as_view(), name='postdelete'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from market.views import post_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # market app url 추가 - 박지수

    path('market/', include('market.urls')),
    path('common/', include('common.urls')),
    path('', post_views.PostList.as_view(), name='postlist'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cloudmarket/common/models.py
from django.db import models

# Create your models here.

cloudmarket/market/models.py
from django.db import models
from django.urls.base import reverse
from imagekit.models import ProcessedImageField #resize
from imagekit.processors import ResizeToFit #resize
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
# Create your models here.

# 게시글 모델
class Post(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    post_title = models.CharField(max_length=50)
    # image = models.ImageField(upload_to='img/', blank=True, null=True)
    image = ProcessedImageField(upload_to='img/', processors=[ResizeToFit(500,500)]) #resize
    content = models.TextField()
    price = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(10000000)])
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

# 댓글 모델
class Comment(models.Model):
    post_id = models.ForeignKey(Post, on_delete=models.CASCADE)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

    

cloudmarket/common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    phone = forms.CharField(label="전화번호")
    address = forms.CharField(label="주소")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "last_name", "phone", "address")

cloudmarket/market/forms.py
from django import forms
from market.models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['post_title', 'image', 'price', 'content']
                
        labels = {
            'post_title' : '글 제목',
            'image': '파일선택',
            'price' : '가격',
            'content': '글 내용'
        }  
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

        widgets = {
          'content': forms.Textarea(attrs={'class': 'form-control', 'rows':2, 'cols':10}),
        }

        labels = {
            'content': '댓글 수정 중...',
        }  

cloudmarket/common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserForm


def signup(request):
    """
    계정생성
    """
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

cloudmarket/common/views/common_views.py
from common.forms import UserForm
from django.views.generic.edit import CreateView
from django.contrib.auth import authenticate, login
from django.urls import reverse_lazy

class CreateUserView(CreateView):  # 제네릭의 CreateView는 폼하고 연결돼서, 혹은 모델하고 연결돼서 새로운 데이터를 넣을 때 사용.
    template_name = 'common/signup.html'     # 회원가입 할 때 띄울 폼 템플릿
    form_class = UserForm
    success_url = reverse_lazy('market:postlist') # 성공하면 어디로 갈지, create_user_done은 url name
    # 여기서 reverse가 아닌 reverse_lazy를 사용하는 이유: 제네릭뷰 같은경우 타이밍 문제 때문에 reverse_lazy를 사용해야함

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


'''
def signup(request):
    """
    계정생성
    """
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('market:postlist')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})
'''

cloudmarket/common/views/login_views.py
from common.forms import UserForm
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy

class CreateUserView(CreateView):  # 제네릭의 CreateView는 폼하고 연결돼서, 혹은 모델하고 연결돼서 새로운 데이터를 넣을 때 사용.
    template_name = 'common/signup.html'     # 회원가입 할 때 띄울 폼 템플릿
    form_class = UserForm
    success_url = reverse_lazy('market:postlist') # 성공하면 어디로 갈지, create_user_done은 url name
    # 여기서 reverse가 아닌 reverse_lazy를 사용하는 이유: 제네릭뷰 같은경우 타이밍 문제 때문에 reverse_lazy를 사용해야함

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


'''
def signup(request):
    """
    계정생성
    """
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('market:postlist')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})
'''

cloudmarket/market/views.py
from django.views.generic import ListView
from .models import Post
from django.shortcuts import render , get_object_or_404, redirect
from django.utils import timezone


# Create your views here.
# CBV(Class Based View) 사용하기


def index(request):
    '''
    post 목록 출력
    '''
    post_list= Post.objects.order_by('-create_date')
    context ={'post_list' : post_list}
    return render(request, 'market/post_list.html', context)

def detail(request, post_id):
    """
    post 내용 출력
    """
    post = get_object_or_404(Post, pk=post_id)
    context = {'post': post}
    return render(request, 'market/post_detail.html', context)

def comment_create(request, post_id):
    '''
    market 댓글 등록
    '''

    post = get_object_or_404(Post, pk=post_id)
    post.comment_set.create(content=request.POST.get('content'), create_date=timezone.now())
    return redirect('market:detail', post_id=post.id)

'''
class PostList(ListView):
    paginate_by = 10
    def get_queryset(self):
        return Post.objects.order_by('-create_date')
'''

cloudmarket/market/views/comment_views.py
from datetime import datetime
from django.shortcuts import get_object_or_404
from django.views.generic import CreateView, DeleteView, UpdateView
from market.models import Comment, Post
from market.forms import CommentForm
from django.utils import timezone
from django.urls import reverse_lazy

# Create your views here.
# CBV(Class Based View) 사용하기


class CommentCreate(CreateView):
    form_class = CommentForm
    template_name = 'market/post_datail.html'
    success_url = reverse_lazy('market:postdetail')

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.post_id = get_object_or_404(Post, pk=self.kwargs['pk'])
        comment.user_id = self.request.user
        comment.create_date = datetime.now()
        comment.save()
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse_lazy('market:postdetail', kwargs={'pk':self.object.post_id.pk}) 


class CommentUpdate(UpdateView):
    form_class = CommentForm
    template_name = 'market/post_detail.html'
    success_url = reverse_lazy('market:postdetail')

    def get_object(self):
        comment = get_object_or_404(Comment, pk=self.kwargs['pk'])
        comment.modify_date = datetime.now()
        comment.save()
        return comment

    def get_success_url(self):
        return reverse_lazy('market:postdetail', kwargs={'pk':self.object.post_id.pk})


class CommentDelete(DeleteView):
    model = Comment
    success_url = '/'
    
    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

    def get_success_url(self):
        return reverse_lazy('market:postdetail', kwargs={'pk':self.object.post_id.pk}) 

#@login_required(login_url='common:login')

cloudmarket/market/views/my_views.py
from django.views.generic import ListView
from market.models import Post, Comment
from django.db.models import Q
from django.urls import reverse_lazy

'''
class BookListView(generic.ListView):
    model = Book
    context_object_name = 'my_book_list'   # your own name for the list as a template variable
    queryset = Book.objects.filter(title__icontains='war')[:5] # Get 5 books containing the title war
    template_name = 'books/my_arbitrary_template_name_list.html'  # Specify your own template name/location
'''

class MyPostList(ListView):
    context_object_name='mypost'
    paginate_by = 5 # 제네릭 뷰의 강력함 : 이 코드 한줄이면 뒤부턴 페이징을 신경쓸 필요가 없다
    template_name='market/mypost_list.html'
    global mypost_list
    
    def get_queryset(self):
        global mypost_list
        mypost_list=Post.objects.order_by('-create_date')
        mypost_list=mypost_list.filter(
            Q(user_id__username=self.request.user.username) 
            #아이디로 비교 user_id__username과 user.username
        ).distinct()
        return mypost_list #return 타입 역시 queryset. 복잡하게 생각말기(render, reverse_lazy 필요없음)

    def get_context_data(self, **kwargs):
        global mypost_list
        # 기본 구현을 호출해 context를 가져온다.
        context = super(MyPostList, self).get_context_data(**kwargs)
        # 모든 책을 쿼리한 집합을 context 객체에 추가한다.
        context['mypost'] = mypost_list
        return context 
        
        
    
    def get_success_url(self):
        return reverse_lazy('market:mypostlist', args=[1])
        
#믹스 인  , 다중상속

class MyCommentList(ListView):
    context_object_name='mycomment'
    paginate_by = 5 # 제네릭 뷰의 강력함 : 이 코드 한줄이면 뒤부턴 페이징을 신경쓸 필요가 없다
    template_name='market/mycomment_list.html'
    global mycomment_list
    
    def get_queryset(self): #오버라이딩해준 것 object list
        global mycomment_list
        mycomment_list=Comment.objects.order_by('-create_date')
        mycomment_list=mycomment_list.filter(
            Q(user_id__username=self.request.user.username) 
            #아이디로 비교 user_id__username과 user.username
        ).distinct()
        return mycomment_list #return 타입 역시 queryset. 복잡하게 생각말기(render, reverse_lazy 필요없음)

    def get_context_data(self, **kwargs):#object list
        global mycomment_list
        # 기본 구현을 호출해 context를 가져온다.
        context = super(MyCommentList, self).get_context_data(**kwargs)
        # 모든 책을 쿼리한 집합을 context 객체에 추가한다.
        context['mycomment'] = mycomment_list
        return context 

cloudmarket/market/views/post_views.py
from datetime import datetime
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from market.models import Post
from market.forms import CommentForm, PostForm
from django.utils import timezone
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
# 시그널(이미지 삭제)
import os
from django.db import models
from django.dispatch import receiver
from django.db.models import Q
from django.contrib.auth.decorators import login_required
#from django.core.paginator import Paginator

# Create your views here.
# CBV(Class Based View) 사용하기

class PostList(ListView):
    paginate_by = 6
    # 자동: context = {'page_obj':page_obj}
    # 제네릭 뷰의 강력함 : 이 코드 한줄이면 뒤부턴 페이징을 신경쓸 필요가 없다
    #template_name = 'templates/market/post_list.html'
    global post_list
    def get_queryset(self):
        global post_list
        #page = self.request.GET.get('page','1') # paging 관련 코드가 필요가 없어짐
        kw = self.request.GET.get('kw','')
        post_list=Post.objects.order_by('-create_date')

        if kw:
            post_list = post_list.filter(
                Q(post_title__icontains=kw) |       # 제목검색
                Q(content__icontains=kw) |          # 내용검색
                Q(user_id__last_name__icontains=kw) #글쓴이 검색
            ).distinct()

        return post_list #return 타입 역시 queryset. 복잡하게 생각말기(render, reverse_lazy 필요없음)
      
        #subject__contains=kw 대신 subject__icontains=kw을 사용하면 대소문자를 가리지 않고 찾아 준다.    
        #filter 함수에서 모델 속성에 접근하기 위해서는 이처럼 __ (언더바 두개) 를 이용하여 하위 속성에 접근할 수 있다.
    def get_context_data(self, *, object_list=None, **kwargs):
        context ={"kw" : self.request.GET.get('kw','')}
        kwargs.update(context)
        return super().get_context_data(**kwargs)

class PostDetail(DetailView):
    model = Post
    template_name = 'market/post_detail.html'
    form_class = CommentForm
    
    def get_context_data(self, **kwargs):
        context = super(PostDetail, self).get_context_data(**kwargs)
        # context['form'] = CommentForm(initial={'content': '',})
        context['form'] = CommentForm
        return context


class PostCreate(CreateView):
    form_class = PostForm
    template_name = 'market/post_create.html'
    success_url = reverse_lazy('market:postdetail')

    def form_valid(self, form):
        post = form.save(commit=False)
        post.user_id = self.request.user
        post.create_date = datetime.now()
        post.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('market:postdetail', kwargs={'pk':self.object.pk})


class PostUpdate(UpdateView):
    form_class = PostForm
    template_name = 'market/post_update.html'
    success_url = reverse_lazy('market:postdetail')

    def get_object(self):
        post = get_object_or_404(Post, pk=self.kwargs['pk'])
        post.modify_date = datetime.now()
        post.save()
        return post
    
    # 이미지 삭제
    @receiver(models.signals.pre_save, sender=Post)
    def auto_delete_file_on_change(sender, instance, **kwargs):
        if not instance.pk:
            return False
        try:
            old_file = Post.objects.get(pk=instance.pk).image
        except Post.DoesNotExist:
            return False
        new_file = instance.image
        if not old_file == new_file:
            if os.path.isfile(old_file.path):
                os.remove(old_file.path)

    def get_success_url(self):
        return reverse_lazy('market:postdetail', kwargs={'pk':self.object.pk})


class PostDelete(DeleteView):
    model = Post
    success_url = '/'

    # 이미지 삭제
    @receiver(models.signals.post_delete, sender=Post)
    def auto_delete_file_on_delete(sender, instance, **kwargs):
        if instance.image:
            if os.path.isfile(instance.image.path):
                os.remove(instance.image.path)

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

cloudmarket/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <!--custom CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <title>Cloud Market</title>
</head>
<body id="bg-gradation">
    {% include "navbar.html" %}
    {% block content %}
    {% endblock %}
    {% block script %}
        <!-- jQuery JS -->
        <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
        <!-- Bootstrap JS -->
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <!-- 자바스크립트 Start -->
        <script src="{% static 'js/event.js' %}"></script>
    {% endblock %}
</body>
</html>

cloudmarket/templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}
<!--
폼 오류에는 다음과 같이 두 가지 종류의 오류가 있다.

필드 오류 (field.errors)
넌필드 오류 (form.non_field_errors)

필드 오류는 사용자가 입력한 필드 값에 대한 오류로 값이 누락되었거나 필드의 형식이 일치하지 않는 경우에 발생하는 오류이다.
넌필드 오류는 필드의 값과는 상관없이 다른 이유로 발생하는 오류이다. form_errors.html 템플릿은 필드 오류와 넌필드 오류
모두를 표시하기 위해 삽입되는 템플릿이다.
-->

cloudmarket/templates/login_base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <!--custom CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <title>Cloud Market</title>
</head>
<body id="bg-gradation">
    {% include "login_navbar.html" %}
    {% block content %}
    {% endblock %}
    {% block script %}
        <!-- jQuery JS -->
        <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    {% endblock %}
</body>
</html>

cloudmarket/templates/login_navbar.html
<nav class="align-center">
      <!-- 로고 -->
      <a class="navbar-brand" href="{% url 'market:postlist' %}">
          <img src="/static/img/cloudlogo.png" width="95" height="61" alt="cloudmarketlogo">
      </a>
</nav>

cloudmarket/templates/navbar.html
<nav class="navbar navbar-expand-lg">

    <div class="container-fluid">
        <!-- 로고 -->
        <a class="navbar-brand" href="{% url 'market:postlist' %}">
            <img src="/static/img/cloudlogo.png" width="95" height="61" alt="cloudmarketlogo">
        </a>

        <!-- 검색 창 -->
        <div class="col-4 input-group search">
            <input type="text" class="form-control kw" value="{{ kw|default_if_none:'' }}" placeholder="검색어를 입력하세요">
            <div class="input-group-append">
                <button class="btn btn-primary" type="button" id="btn_search">찾기</button>
            </div>
        </div>

        <!-- 드롭 다운  -->
        <span class="col-3 mystatus">
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                <div>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ user.last_name }}님
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'common:logout' %}">로그아웃</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'market:mypostlist' %}">내가 쓴 게시글</a>
                            <a class="dropdown-item" href="{% url 'market:mycommentlist' %}">내가 쓴 댓글</a>
                        </div>
                    </li>
                </div>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                </li>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>
<!-- 검색 폼  -->
<form id="searchForm" method="get" action="{% url 'market:postlist' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>