cloudmarket/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import login_views
app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', login_views.CreateUserView.as_view(), name='signup'),
]

cloudmarket/market/urls.py
from django.urls import path
from .views import post_views, comment_views, my_views

# 이미지
# from django.conf.urls.static import static
# from django.conf import settings


app_name = 'market'


urlpatterns = [

    path('', post_views.PostList.as_view(), name='postlist'),
    path('<int:pk>/', post_views.PostDetail.as_view(), name = 'postdetail' ),

    path('post/create/', post_views.PostCreate.as_view(), name = 'postcreate' ),
    path('post/update/<int:pk>/', post_views.PostUpdate.as_view(), name='postupdate'),
    path('post/delete/<int:pk>/', post_views.PostDelete.as_view(), name='postdelete'),

    path('comment/create/<int:pk>/', comment_views.CommentCreate.as_view(), name='commentcreate'),
    path('comment/update/<int:pk>/', comment_views.CommentUpdate.as_view(), name='commentupdate'),
    path('comment/delete/<int:pk>/', comment_views.CommentDelete.as_view(), name='commentdelete'),

    path('postlist/', my_views.MyPostList.as_view(), name='mypostlist'),
    path('commentlist/', my_views.MyCommentList.as_view(), name='mycommentlist'),
]

market/urls.py
from django.urls import path
from .views import post_views

# 이미지
# from django.conf.urls.static import static
# from django.conf import settings

# 네임스페이스 추가 - 박지수
app_name = 'market'


urlpatterns = [
    # post_views.py - 박지수
    path('', post_views.PostList.as_view(), name='postlist'),
    path('create/', post_views.PostCreate.as_view(), name = 'postcreate' ),
    path('<int:pk>/', post_views.PostDetail.as_view(), name = 'postdetail' ),
    path('update/<int:pk>/', post_views.PostUpdate.as_view(), name='postupdate'),
    path('delete/<int:pk>/', post_views.PostDelete.as_view(), name='postdelete'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from market.views import post_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # market app url 추가 - 박지수

    path('market/', include('market.urls')),
    path('common/', include('common.urls')),
    path('', post_views.PostList.as_view(), name='postlist'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cloudmarket/common/models.py
from django.db import models

# Create your models here.

cloudmarket/market/models.py
from django.db import models
from django.urls.base import reverse
from imagekit.models import ProcessedImageField #resize
from imagekit.processors import ResizeToFit #resize
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
# Create your models here.

# 게시글 모델
class Post(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    post_title = models.CharField(max_length=50)
    # image = models.ImageField(upload_to='img/', blank=True, null=True)
    image = ProcessedImageField(upload_to='img/', processors=[ResizeToFit(500,500)]) #resize
    content = models.TextField()
    price = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(10000000)])
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

# 댓글 모델
class Comment(models.Model):
    post_id = models.ForeignKey(Post, on_delete=models.CASCADE)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

    

cloudmarket/common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    phone = forms.CharField(label="전화번호")
    address = forms.CharField(label="주소")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "last_name", "phone", "address")

cloudmarket/market/forms.py
from django import forms
from market.models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['post_title', 'image', 'price', 'content']
                
        labels = {
            'post_title' : '글 제목',
            'image': '파일선택',
            'price' : '가격',
            'content': '글 내용'
        }  
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

        widgets = {
          'content': forms.Textarea(attrs={'class': 'form-control', 'rows':2, 'cols':10}),
        }

        labels = {
            'content': '댓글 수정 중...',
        }  

market/forms.py
from django import forms
from market.models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['post_title', 'image', 'content', 'price']

cloudmarket/common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserForm


def signup(request):
    """
    계정생성
    """
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

cloudmarket/common/views/common_views.py
from common.forms import UserForm
from django.views.generic.edit import CreateView
from django.contrib.auth import authenticate, login
from django.urls import reverse_lazy

class CreateUserView(CreateView):  # 제네릭의 CreateView는 폼하고 연결돼서, 혹은 모델하고 연결돼서 새로운 데이터를 넣을 때 사용.
    template_name = 'common/signup.html'     # 회원가입 할 때 띄울 폼 템플릿
    form_class = UserForm
    success_url = reverse_lazy('market:postlist') # 성공하면 어디로 갈지, create_user_done은 url name
    # 여기서 reverse가 아닌 reverse_lazy를 사용하는 이유: 제네릭뷰 같은경우 타이밍 문제 때문에 reverse_lazy를 사용해야함

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


'''
def signup(request):
    """
    계정생성
    """
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('market:postlist')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})
'''

cloudmarket/common/views/login_views.py
from common.forms import UserForm
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy

class CreateUserView(CreateView):  # 제네릭의 CreateView는 폼하고 연결돼서, 혹은 모델하고 연결돼서 새로운 데이터를 넣을 때 사용.
    template_name = 'common/signup.html'     # 회원가입 할 때 띄울 폼 템플릿
    form_class = UserForm
    success_url = reverse_lazy('market:postlist') # 성공하면 어디로 갈지, create_user_done은 url name
    # 여기서 reverse가 아닌 reverse_lazy를 사용하는 이유: 제네릭뷰 같은경우 타이밍 문제 때문에 reverse_lazy를 사용해야함

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


'''
def signup(request):
    """
    계정생성
    """
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('market:postlist')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})
'''

cloudmarket/market/views.py
from django.views.generic import ListView
from .models import Post
from django.shortcuts import render , get_object_or_404, redirect
from django.utils import timezone


# Create your views here.
# CBV(Class Based View) 사용하기


def index(request):
    '''
    post 목록 출력
    '''
    post_list= Post.objects.order_by('-create_date')
    context ={'post_list' : post_list}
    return render(request, 'market/post_list.html', context)

def detail(request, post_id):
    """
    post 내용 출력
    """
    post = get_object_or_404(Post, pk=post_id)
    context = {'post': post}
    return render(request, 'market/post_detail.html', context)

def comment_create(request, post_id):
    '''
    market 댓글 등록
    '''

    post = get_object_or_404(Post, pk=post_id)
    post.comment_set.create(content=request.POST.get('content'), create_date=timezone.now())
    return redirect('market:detail', post_id=post.id)

'''
class PostList(ListView):
    paginate_by = 10
    def get_queryset(self):
        return Post.objects.order_by('-create_date')
'''

cloudmarket/market/views/comment_views.py
from datetime import datetime
from django.shortcuts import get_object_or_404
from django.views.generic import CreateView, DeleteView, UpdateView
from market.models import Comment, Post
from market.forms import CommentForm
from django.utils import timezone
from django.urls import reverse_lazy

# Create your views here.
# CBV(Class Based View) 사용하기


class CommentCreate(CreateView):
    form_class = CommentForm
    template_name = 'market/post_datail.html'
    success_url = reverse_lazy('market:postdetail')

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.post_id = get_object_or_404(Post, pk=self.kwargs['pk'])
        comment.user_id = self.request.user
        comment.create_date = datetime.now()
        comment.save()
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse_lazy('market:postdetail', kwargs={'pk':self.object.post_id.pk}) 


class CommentUpdate(UpdateView):
    form_class = CommentForm
    template_name = 'market/post_detail.html'
    success_url = reverse_lazy('market:postdetail')

    def get_object(self):
        comment = get_object_or_404(Comment, pk=self.kwargs['pk'])
        comment.modify_date = datetime.now()
        comment.save()
        return comment

    def get_success_url(self):
        return reverse_lazy('market:postdetail', kwargs={'pk':self.object.post_id.pk})


class CommentDelete(DeleteView):
    model = Comment
    success_url = '/'
    
    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

    def get_success_url(self):
        return reverse_lazy('market:postdetail', kwargs={'pk':self.object.post_id.pk}) 

#@login_required(login_url='common:login')

cloudmarket/market/views/my_views.py
from django.views.generic import ListView
from market.models import Post, Comment
from django.db.models import Q
from django.urls import reverse_lazy

'''
class BookListView(generic.ListView):
    model = Book
    context_object_name = 'my_book_list'   # your own name for the list as a template variable
    queryset = Book.objects.filter(title__icontains='war')[:5] # Get 5 books containing the title war
    template_name = 'books/my_arbitrary_template_name_list.html'  # Specify your own template name/location
'''

class MyPostList(ListView):
    context_object_name='mypost'
    paginate_by = 5 # 제네릭 뷰의 강력함 : 이 코드 한줄이면 뒤부턴 페이징을 신경쓸 필요가 없다
    template_name='market/mypost_list.html'
    global mypost_list
    
    def get_queryset(self):
        global mypost_list
        mypost_list=Post.objects.order_by('-create_date')
        mypost_list=mypost_list.filter(
            Q(user_id__username=self.request.user.username) 
            #아이디로 비교 user_id__username과 user.username
        ).distinct()
        return mypost_list #return 타입 역시 queryset. 복잡하게 생각말기(render, reverse_lazy 필요없음)

    def get_context_data(self, **kwargs):
        global mypost_list
        # 기본 구현을 호출해 context를 가져온다.
        context = super(MyPostList, self).get_context_data(**kwargs)
        # 모든 책을 쿼리한 집합을 context 객체에 추가한다.
        context['mypost'] = mypost_list
        return context 
        
        
    
    def get_success_url(self):
        return reverse_lazy('market:mypostlist', args=[1])
        
#믹스 인  , 다중상속

class MyCommentList(ListView):
    context_object_name='mycomment'
    paginate_by = 5 # 제네릭 뷰의 강력함 : 이 코드 한줄이면 뒤부턴 페이징을 신경쓸 필요가 없다
    template_name='market/mycomment_list.html'
    global mycomment_list
    
    def get_queryset(self): #오버라이딩해준 것 object list
        global mycomment_list
        mycomment_list=Comment.objects.order_by('-create_date')
        mycomment_list=mycomment_list.filter(
            Q(user_id__username=self.request.user.username) 
            #아이디로 비교 user_id__username과 user.username
        ).distinct()
        return mycomment_list #return 타입 역시 queryset. 복잡하게 생각말기(render, reverse_lazy 필요없음)

    def get_context_data(self, **kwargs):#object list
        global mycomment_list
        # 기본 구현을 호출해 context를 가져온다.
        context = super(MyCommentList, self).get_context_data(**kwargs)
        # 모든 책을 쿼리한 집합을 context 객체에 추가한다.
        context['mycomment'] = mycomment_list
        return context 

cloudmarket/market/views/post_views.py
from datetime import datetime
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from market.models import Post
from market.forms import CommentForm, PostForm
from django.utils import timezone
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
# 시그널(이미지 삭제)
import os
from django.db import models
from django.dispatch import receiver
from django.db.models import Q
from django.contrib.auth.decorators import login_required
#from django.core.paginator import Paginator

# Create your views here.
# CBV(Class Based View) 사용하기

class PostList(ListView):
    paginate_by = 6
    # 자동: context = {'page_obj':page_obj}
    # 제네릭 뷰의 강력함 : 이 코드 한줄이면 뒤부턴 페이징을 신경쓸 필요가 없다
    #template_name = 'templates/market/post_list.html'
    global post_list
    def get_queryset(self):
        global post_list
        #page = self.request.GET.get('page','1') # paging 관련 코드가 필요가 없어짐
        kw = self.request.GET.get('kw','')
        post_list=Post.objects.order_by('-create_date')

        if kw:
            post_list = post_list.filter(
                Q(post_title__icontains=kw) |       # 제목검색
                Q(content__icontains=kw) |          # 내용검색
                Q(user_id__last_name__icontains=kw) #글쓴이 검색
            ).distinct()

        return post_list #return 타입 역시 queryset. 복잡하게 생각말기(render, reverse_lazy 필요없음)
      
        #subject__contains=kw 대신 subject__icontains=kw을 사용하면 대소문자를 가리지 않고 찾아 준다.    
        #filter 함수에서 모델 속성에 접근하기 위해서는 이처럼 __ (언더바 두개) 를 이용하여 하위 속성에 접근할 수 있다.
    def get_context_data(self, *, object_list=None, **kwargs):
        context ={"kw" : self.request.GET.get('kw','')}
        kwargs.update(context)
        return super().get_context_data(**kwargs)

class PostDetail(DetailView):
    model = Post
    template_name = 'market/post_detail.html'
    form_class = CommentForm
    
    def get_context_data(self, **kwargs):
        context = super(PostDetail, self).get_context_data(**kwargs)
        # context['form'] = CommentForm(initial={'content': '',})
        context['form'] = CommentForm
        return context


class PostCreate(CreateView):
    form_class = PostForm
    template_name = 'market/post_create.html'
    success_url = reverse_lazy('market:postdetail')

    def form_valid(self, form):
        post = form.save(commit=False)
        post.user_id = self.request.user
        post.create_date = datetime.now()
        post.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('market:postdetail', kwargs={'pk':self.object.pk})


class PostUpdate(UpdateView):
    form_class = PostForm
    template_name = 'market/post_update.html'
    success_url = reverse_lazy('market:postdetail')

    def get_object(self):
        post = get_object_or_404(Post, pk=self.kwargs['pk'])
        post.modify_date = datetime.now()
        post.save()
        return post
    
    # 이미지 삭제
    @receiver(models.signals.pre_save, sender=Post)
    def auto_delete_file_on_change(sender, instance, **kwargs):
        if not instance.pk:
            return False
        try:
            old_file = Post.objects.get(pk=instance.pk).image
        except Post.DoesNotExist:
            return False
        new_file = instance.image
        if not old_file == new_file:
            if os.path.isfile(old_file.path):
                os.remove(old_file.path)

    def get_success_url(self):
        return reverse_lazy('market:postdetail', kwargs={'pk':self.object.pk})


class PostDelete(DeleteView):
    model = Post
    success_url = '/'

    # 이미지 삭제
    @receiver(models.signals.post_delete, sender=Post)
    def auto_delete_file_on_delete(sender, instance, **kwargs):
        if instance.image:
            if os.path.isfile(instance.image.path):
                os.remove(instance.image.path)

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

cloudmarket/templates/market/post_create.html
{% extends 'base.html' %}
{% block content %}
<div class="container contact">
  <div class="row">
    <div class="col-md-3">
      <div class="contact-info">
        <img src="/static/img/cloud.png" width="70" height="58" alt="image" />
        <h2>구름마켓</h2>
        <h4>상품</h4>
        <h4>등록하기</h4>
      </div>
    </div>
    <div class="col-md-9">
      <form method="post" class="post-form my-3" enctype="multipart/form-data" action=".">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="contact-form">
          <div class="form-group">
            <label class="control-label col-sm-2" for="fname">글 제목</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" id="post_title"
                value="{{ form.post_title.value|default_if_none:'' }}" placeholder="제목을 입력해주세요(50자 내)"
                name="post_title">
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-10">
              <input type="file" id="image" value="{{ form.image.value|default_if_none:'' }}" name="image">
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-sm-2" for="email">가격</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" id="price" value="{{ form.price.value|default_if_none:'' }}"
                placeholder="가격을 입력해주세요(&#8361)" name="price">
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-sm-2" for="contentt">글 내용</label>
            <div class="col-sm-10">
              <textarea class="form-control" rows="5" id="content" value="{{ form.content.value|default_if_none:'' }}"
                placeholder="구매일자, 모델명, 흠집 등 자세히 작성해주세요!" name="content"></textarea>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10 button-text-align">
              <input type="submit" class="btn btn-primary" value="등록하기" ></button>
              <input type="button" class="btn btn-primary" value="취소하기" onclick="history.back(-1);">
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

cloudmarket/templates/market/post_detail.html
{% extends 'base.html' %}
{% load humanize %}
{% block content %}
<br>
<br>
<div class="container rounded detail-background">
    <!-- 게시글 -->
    <br>
    <div class="align-center">
        <h3 class="align-center">{{ post.post_title }}</h3>
        <hr>
        <div class="align-right-90">
         {{ post.user_id.last_name }} | {% if post.modify_date %} {{ post.modify_date }}(수정) {% else %} {{ post.create_date }} {% endif %} 
        </div>

        <br>
        <br>
        
        {% if post.image %}
         <img src="{{ post.image.url }}" alt="{{ post.image }}"> 
        {% else %}
         <img src="/static/img/noimage.png" alt="이미지가 없습니다">
        {% endif %}
        
        <br> 
        <br>

        <p class="detail-price">{{ post.price|intcomma }}원</p>
        <br>
        <div class="detail-content">{{ post.content }}</div>

        {% if request.user == post.user_id %}
        <div class="detail-btn">
            <a class="btn btn-primary" href="{% url 'market:postupdate' post.id  %}" >수정</a>
            <a class="btn btn-primary" href="{% url 'market:postdelete' post.id  %}" >삭제</a>
        </div>
        {% endif %}
    </div>
    
 <hr>

    <!-- 댓글 목록 -->
    <h5 class="comment"><span class="detail-comment-count">{{ post.comment_set.count }}</span>개의 댓글이 있습니다.</h5>
    <!-- 댓글 수정 -->
    {% for comment in post.comment_set.all %}
    <div class="mt-3">
        <div class="comment py-2 text-muted" id="divToggle1{{ comment.id }}">
            <p>{{ comment.user_id.last_name }} | {% if comment.modify_date %} {{ comment.modify_date }}(수정) {% else %} {{ comment.create_date }} {% endif %}</p>
            <p id="comment-list">{{ comment.content }}</p>
            {% if request.user == comment.user_id %}
            <div class="comupdate1-btn">
            <input type="button" class="btn btn-primary" value="수정" id="button1{{ comment.id }}">
            <a class="btn btn-primary" href="{% url 'market:commentdelete' comment.id  %}" >삭제</a>
            </div>
        </div>
        <div class="comment py-2 text-muted com-hidden" id="divToggle2{{ comment.id }}">
            <form method="post" class="post-form my-3" action="{% url 'market:commentupdate' comment.pk %}">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="comupdate2-btn">
                <input type="submit" class="btn btn-primary" value="저장">
                <input type="button" class="btn btn-primary" value="이전" id="button2{{ comment.id }}">
                </div>
            </form>
        </div>
        {% endif %}
        
    </div>
 <hr>
    {% endfor %}

    <!-- 댓글 작성 -->
    <br>
    <form action="{% url 'market:commentcreate' post.id  %}" method="post" {% if not user.is_authenticated %}hidden{% endif %}
    class="most-used-csh">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <textarea class="comment" name="content" id="comment-content" value="{{ form.username.value|default_if_none:'' }}"required></textarea>
        <input type="submit" class="btn btn-primary comcreate-btn" name='create' id='create' value="등록">
    </form>
    </div>
</div>
{% endblock %}

cloudmarket/templates/market/post_list.html
{% extends 'base.html' %}
{% load humanize %}
{% block content %}
<br>
<br>
<!--리스트창-->
{% if page_obj %}
    {% for post in page_obj %}
    <div class="listmargin">
     <ul class="float-left">
        <div class="cols-3">
            
         <a href="/market/{{ post.id }}/">
            {% if post.image %}
            <img class="imglist rounded" src="{{ post.image.url }}" alt="{{ post.image }}"><br>
            {% else %}
            <img class="imglist rounded" src="/static/img/noimage.png" alt="이미지가 없습니다"><br>
            {% endif %}
            
            <div class="listtext">
                <h5>{{ post.post_title }}</h5>
                {{ post.price|intcomma }}원<br>
                {{ post.user_id.last_name }}<br>
                {% if post.modify_date %}
                {{ post.modify_date }}(수정)<br>        
                {% else %}
                {{ post.create_date }}
                {% endif %} 
            </div>
         </a>
        </div>
     </ul>
    </div>
    {% endfor %}
<div class="clearfix"></div>
{% else %}
    <p class="no-post-comment">검색 결과가 없습니다:(</p>
{% endif %}

<!-- 게시글 작성 버튼 -->
<div class="rightbutton">
    <a class="btn btn-primary float-right" href="{% url 'market:postcreate' %}" {% if not user.is_authenticated %}hidden{% endif %}>작성</a>
</div>

<!-- 페이징처리 시작 -->
<ul class="pagination justify-content-center">

    <!-- 이전페이지 -->
    {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page="{{ page_obj.previous_page_number }}" href="#"><<</a>
        </li>
    {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#"><<</a>
        </li>
    {% endif %}
    
    <!-- 페이지리스트 -->
    {% for page_number in page_obj.paginator.page_range %}
    {% if page_number >= page_obj.number|add:-5 and page_number <= page_obj.number|add:5 %}
    {% if page_number == page_obj.number %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
        </li>
    {% else %}
        <li class="page-item">
            <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
        </li>
    {% endif %}
    {% endif %}
    {% endfor %}

    <!-- 다음페이지 -->
    {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ page_obj.next_page_number }}"  href="#">>></a>
        </li>
    {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">>></a>
        </li>
    {% endif %}
</ul>
{% endblock %}

cloudmarket/templates/market/post_update.html
{% extends 'base.html' %}
{% block content %}
<!-- 상품 재등록 -->
<div class="container contact">
  <div class="row">
    <div class="col-md-3">
      <div class="contact-info">
        <img src="/static/img/cloud.png" width="70" height="58" alt="image" />
        <h2>구름마켓</h2>
        <h4>게시글</h4>
        <h4>수정하기</h4>
      </div>
    </div>
    <div class="col-md-9">
      <form method="post" class="post-form my-3" enctype="multipart/form-data"
        action="{% url 'market:postupdate' post.pk %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="contact-form">
          <div class="form-group">
            <label class="control-label col-sm-2" for="fname">글 제목</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" id="post_title"
                value="{{ form.post_title.value|default_if_none:'' }}" placeholder="제목을 입력해주세요(50자 내)"
                name="post_title">
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-10">
              {{ form.image }}
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-sm-2" for="email">가격</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" id="price" value="{{ form.price.value|default_if_none:'' }}"
                placeholder="가격을 입력해주세요(&#8361;)" name="price">
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-sm-2" for="contentt">글 내용</label>
            <div class="col-sm-10">
              <textarea class="form-control" rows="5" id="content" value="{{ form.content.value|default_if_none:'' }}"
                placeholder="구매일자, 모델명, 흠집 등 자세히 작성해주세요!" name="content">{{form.content.value}}</textarea>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <input type="submit" class="btn btn-primary" value="수정하기"></button>
              <input type="button" class="btn btn-primary" value="취소하기" onclick="history.back(-2);">
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}