cloudmarket/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import login_views
app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', login_views.CreateUserView.as_view(), name='signup'),
]

cloudmarket/project/urls.py
from django.contrib import admin
from django.urls import path, include
from market.views import post_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('admin/', admin.site.urls),
    path('market/', include('market.urls')),
    path('common/', include('common.urls')),
    path('', post_views.PostList.as_view(), name='postlist'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

market/urls.py
from django.urls import path
from .views import post_views

# 이미지
# from django.conf.urls.static import static
# from django.conf import settings

# 네임스페이스 추가 - 박지수
app_name = 'market'


urlpatterns = [
    # post_views.py - 박지수
    path('', post_views.PostList.as_view(), name='postlist'),
    path('create/', post_views.PostCreate.as_view(), name = 'postcreate' ),
    path('<int:pk>/', post_views.PostDetail.as_view(), name = 'postdetail' ),
    path('update/<int:pk>/', post_views.PostUpdate.as_view(), name='postupdate'),
    path('delete/<int:pk>/', post_views.PostDelete.as_view(), name='postdelete'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from market.views import post_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # market app url 추가 - 박지수

    path('market/', include('market.urls')),
    path('common/', include('common.urls')),
    path('', post_views.PostList.as_view(), name='postlist'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">


    <title>Cloud Market</title>
</head>
<body>
    {% include "navbar.html" %}
    {% block content %}
    {% endblock %}
</body>
</html>

templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'market:postlist' %}">구름마켓</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item ">
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'common:logout' %}">(로그아웃)</a>
                {% else %}
                <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                {% endif %}
            </li>
        </ul> 
    </div>
</nav>